#pragma once

#define PORT_CHUNK_SERVER		PORT_PLUS_SERVER_START+0

#define GAME_ID					221

#define PORT_ONLINESVR			60250

enum SOCKCILENT_INDEX{
	SOCKCILENT_ONLINESVR = 10,
	SOCKCILENT_TRANKGAME,
	SOCKCILENT_MAX
};
